### ISSUE TITLE
Adding more tests

### ISSUE THREAD

**Issue by vertoforce** [vertoforce/go-ioc#2]
This would be a great and simple first contribution.  I just need some more tests for IOCs (indicators of compromise) fanging an defanging.
This library has functionality to take a URL in a format like this http[:]//google[.]com and "fang" it to http://google.com and I have some tests in [this file][testfile].  I could use some more to make sure I'm not missing edge cases.

Plus if you find an edge case it should be an easy thing to fix.

[testfile]: https://github.com/vertoforce/go-ioc/blob/master/ioc/defang_test.go

**Comment by flyhard** [comment]
Did some improvements on the tests. Not quite sure if this was exactly what you were thinking of, only how I understood the issue. I am welcoming hints on how to improve my PR.
